id: I661B7366
legacy_id: P001812
ocr_import_info:
  bdrc_scan_id: W8LS18063
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T11:34:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:05:45.228271+00:00'
last_modified: 2022-09-04 12:05:50.103871
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS18063
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS18063
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་སྐྱོང་རྣམས་ཀྱི་གཏོར་འབུལ་དང་གསེར་སྐྱེམས།
statistics:
  ocr_word_mean_confidence_index: 0.6905582856292062
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I8LS18085:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS18085
      total_pages: 50
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS18085.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6905582856292062
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
