id: I661B7366
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T11:35:17+00:00'
last_modified: '2022-06-07T15:14:34.432780+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18063
  title: ཆོས་སྐྱོང་རྣམས་ཀྱི་གཏོར་འབུལ་དང་གསེར་སྐྱེམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4C82:
      image_group_id: I8LS18085
      title: ''
      total_pages: 50
      order: 1
      base_file: 4C82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
