id: P001812
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:22:59.354285
source_metadata:
  id: bdr:W8LS18063
  title: ཆོས་སྐྱོང་རྣམས་ཀྱི་གཏོར་འབུལ་དང་གསེར་སྐྱེམས།
  author: ''
  volumes:
    9790ad4965f043ce859be0f8097130c0:
      image_group_id: I8LS18085
      title: ''
      volume_number: 1
      total_pages: 50
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
